basePath: /api
consumes:
- application/json
definitions:
  entities.Application:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      workspace_id:
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  gateway.Error:
    properties:
      code:
        type: string
      error:
        type: string
    type: object
  sdkapi.ApplicationCreateReq:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  sdkapi.ApplicationCreateRes:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      workspace_id:
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  sdkapi.ApplicationDeleteRes:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      workspace_id:
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  sdkapi.ApplicationGetRes:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      workspace_id:
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  sdkapi.ApplicationListRes:
    properties:
      cursor:
        type: string
      data:
        items:
          $ref: '#/definitions/entities.Application'
        type: array
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@kanthorlabs.com
    name: Kanthor Support
    url: http://kanthorlabs.com/support
  description: SKD API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kanthorlabs.com/terms/
  title: Kanthor SDK API
  version: "1.0"
paths:
  /application:
    get:
      parameters:
      - description: current query cursor
        in: query
        name: _cursor
        type: string
      - description: search keyword
        in: query
        name: _q
        type: string
      - description: limit returning records
        in: query
        maximum: 30
        minimum: 5
        name: _limit
        type: integer
      - collectionFormat: csv
        description: only return records with selected ids
        in: query
        items:
          type: string
        name: _id
        type: array
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.ApplicationListRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - application
    post:
      parameters:
      - description: application properties
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/sdkapi.ApplicationCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.ApplicationCreateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - application
  /application/{id}:
    delete:
      parameters:
      - description: application id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.ApplicationDeleteRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - application
    get:
      parameters:
      - description: application id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.ApplicationGetRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - application
produces:
- application/json
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
