basePath: /api
consumes:
- application/json
definitions:
  entities.Application:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      workspace_id:
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  entities.Endpoint:
    properties:
      app_id:
        type: string
      created_at:
        type: integer
      id:
        type: string
      method:
        description: 'HTTP: POST/PUT/PATCH'
        type: string
      name:
        type: string
      secret_key:
        type: string
      updated_at:
        type: integer
      uri:
        description: |-
          format: scheme ":" ["//" authority] path ["?" query] ["#" fragment]
          HTTP: https:://httpbin.org/post?app=kanthor.webhook
          gRPC: grpc:://app.kanthorlabs.com
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  gateway.Error:
    properties:
      code:
        type: string
      error:
        type: string
    type: object
  sdkapi.ApplicationCreateReq:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  sdkapi.ApplicationCreateRes:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      workspace_id:
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  sdkapi.ApplicationDeleteRes:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      workspace_id:
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  sdkapi.ApplicationGetRes:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      workspace_id:
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  sdkapi.ApplicationListRes:
    properties:
      cursor:
        type: string
      data:
        items:
          $ref: '#/definitions/entities.Application'
        type: array
    type: object
  sdkapi.ApplicationUpdateReq:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  sdkapi.ApplicationUpdateRes:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      workspace_id:
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  sdkapi.EndpointCreateReq:
    properties:
      method:
        enum:
        - POST
        - PUT
        type: string
      name:
        type: string
      secret_key:
        maxLength: 32
        minLength: 16
        type: string
      uri:
        example: https://example.com
        type: string
    required:
    - method
    - name
    - uri
    type: object
  sdkapi.EndpointCreateRes:
    properties:
      app_id:
        type: string
      created_at:
        type: integer
      id:
        type: string
      method:
        description: 'HTTP: POST/PUT/PATCH'
        type: string
      name:
        type: string
      secret_key:
        type: string
      updated_at:
        type: integer
      uri:
        description: |-
          format: scheme ":" ["//" authority] path ["?" query] ["#" fragment]
          HTTP: https:://httpbin.org/post?app=kanthor.webhook
          gRPC: grpc:://app.kanthorlabs.com
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  sdkapi.EndpointDeleteRes:
    properties:
      app_id:
        type: string
      created_at:
        type: integer
      id:
        type: string
      method:
        description: 'HTTP: POST/PUT/PATCH'
        type: string
      name:
        type: string
      secret_key:
        type: string
      updated_at:
        type: integer
      uri:
        description: |-
          format: scheme ":" ["//" authority] path ["?" query] ["#" fragment]
          HTTP: https:://httpbin.org/post?app=kanthor.webhook
          gRPC: grpc:://app.kanthorlabs.com
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  sdkapi.EndpointGetRes:
    properties:
      app_id:
        type: string
      created_at:
        type: integer
      id:
        type: string
      method:
        description: 'HTTP: POST/PUT/PATCH'
        type: string
      name:
        type: string
      secret_key:
        type: string
      updated_at:
        type: integer
      uri:
        description: |-
          format: scheme ":" ["//" authority] path ["?" query] ["#" fragment]
          HTTP: https:://httpbin.org/post?app=kanthor.webhook
          gRPC: grpc:://app.kanthorlabs.com
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  sdkapi.EndpointListRes:
    properties:
      cursor:
        type: string
      data:
        items:
          $ref: '#/definitions/entities.Endpoint'
        type: array
    type: object
  sdkapi.EndpointUpdateReq:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  sdkapi.EndpointUpdateRes:
    properties:
      app_id:
        type: string
      created_at:
        type: integer
      id:
        type: string
      method:
        description: 'HTTP: POST/PUT/PATCH'
        type: string
      name:
        type: string
      secret_key:
        type: string
      updated_at:
        type: integer
      uri:
        description: |-
          format: scheme ":" ["//" authority] path ["?" query] ["#" fragment]
          HTTP: https:://httpbin.org/post?app=kanthor.webhook
          gRPC: grpc:://app.kanthorlabs.com
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@kanthorlabs.com
    name: Kanthor Support
    url: http://kanthorlabs.com/support
  description: SKD API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kanthorlabs.com/terms/
  title: Kanthor SDK API
  version: "1.0"
paths:
  /application:
    get:
      parameters:
      - description: current query cursor
        in: query
        maxLength: 32
        minLength: 29
        name: _cursor
        type: string
      - description: search keyword
        in: query
        maxLength: 32
        minLength: 2
        name: _q
        type: string
      - description: limit returning records
        in: query
        maximum: 30
        minimum: 5
        name: _limit
        type: integer
      - collectionFormat: csv
        description: only return records with selected ids
        in: query
        items:
          type: string
        name: _id
        type: array
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.ApplicationListRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - application
    post:
      parameters:
      - description: application properties
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/sdkapi.ApplicationCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.ApplicationCreateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - application
  /application/{app_id}:
    delete:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.ApplicationDeleteRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - application
    get:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.ApplicationGetRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - application
    put:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        type: string
      - description: application properties
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/sdkapi.ApplicationUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.ApplicationUpdateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - application
  /application/{app_id}/endpoint:
    get:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        type: string
      - description: current query cursor
        in: query
        maxLength: 32
        minLength: 29
        name: _cursor
        type: string
      - description: search keyword
        in: query
        maxLength: 32
        minLength: 2
        name: _q
        type: string
      - description: limit returning records
        in: query
        maximum: 30
        minimum: 5
        name: _limit
        type: integer
      - collectionFormat: csv
        description: only return records with selected ids
        in: query
        items:
          type: string
        name: _id
        type: array
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.EndpointListRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - endpoint
    post:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        type: string
      - description: endpoint properties
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/sdkapi.EndpointCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.EndpointCreateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - endpoint
  /application/{app_id}/endpoint/{ep_id}:
    delete:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        type: string
      - description: endpoint id
        in: path
        name: ep_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.EndpointDeleteRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - endpoint
    get:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        type: string
      - description: endpoint id
        in: path
        name: ep_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.EndpointGetRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - endpoint
    put:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        type: string
      - description: endpoint id
        in: path
        name: ep_id
        required: true
        type: string
      - description: endpoint properties
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/sdkapi.EndpointUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sdkapi.EndpointUpdateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - BasicAuth: []
      tags:
      - endpoint
produces:
- application/json
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
