# normal
bucket:
  layout: "20060102"

# components
logger:
  pretty: true
  level: debug
  with:
    environment: localhost

streaming:
  uri: nats://127.0.0.1:4222
  stream:
    name: default
    subjects:
      - kanthor.default.>
    replicas: 0
    limits:
      msgs: 50000
      msg_bytes: 65536
      # 64kb * 50000 ~ 3Gb
      bytes: 3276800000
      # 60*60*24*3 = 3d
      age: 259200

database:
  uri: sqlite3://./.kanthor/database.sqlite

cache:
  uri: memory://bigcache
  time_to_live: 300000

datastore:
  uri: sqlite3://./.kanthor/datastore.sqlite

# services
migration:
  source: file://./migration/scripts/sql

dataplane:
  grpc:
    addr: ":8181"
  metrics:
    enable: false
    namespace: kanthor
    exporter:
      addr: ":9190"

scheduler:
  subscriber:
    topic: schedule
    group: default
    filter_subject: kanthor.default.msg.>
    temporary: true
    max_deliver: 1
  metrics:
    enable: false
    namespace: kanthor
    exporter:
      addr: ":9290"

dispatcher:
  subscriber:
    topic: dispatch
    group: default
    filter_subject: kanthor.default.req.>
    temporary: true
    max_deliver: 1
  sender:
    timeout: 1500
    retry:
      count: 1
      wait_time: 100
      wait_time_max: 2000
  circuit_breaker:
    timeout: 3000
    sleep_window: 300000
    error_percent_threshold: 10
  metrics:
    enable: false
    namespace: kanthor
    exporter:
      addr: ":9390"