bucket:
  layout: "20060102"

streaming:
  uri: nats://127.0.0.1:4222
  stream:
    name: default
    subjects:
      - kanthor.default.>
    replicas: 0
    limits:
      msgs: 50000
      msg_bytes: 65536
      # 64kb * 50000 ~ 3Gb
      bytes: 3276800000
      # 60*60*24*3 = 3d
      age: 259200

database:
  uri: sqlite3://./.tmp/kanthor.database.sqlite

datastore:
  uri: sqlite3://./.tmp/kanthor.datastore.sqlite

migration:
  logger:
    pretty: true
    level: debug
    with:
      app: migration
  source: file://./migration/scripts/sql

dataplane:
  logger:
    pretty: true
    level: debug
    with:
      app: dataplane
  server:
    addr: ":8080"