# normal
bucket:
  layout: "20060102"

# components
logger:
  pretty: true
  level: debug
  with:
    environment: localhost

streaming:
  uri: nats://127.0.0.1:4222
  stream:
    name: default
    subjects:
      - kanthor.default.>
    replicas: 0
    limits:
      msgs: 50000
      msg_bytes: 65536
      # 64kb * 50000 ~ 3Gb
      bytes: 3276800000
      # 60*60*24*3 = 3d
      age: 259200

database:
  uri: sqlite3://./.kanthor/database.sqlite

cache:
  uri: memory://bigcache
  time_to_live: 300000

datastore:
  uri: sqlite3://./.kanthor/datastore.sqlite

# services
migration:
  tasks:
    - name: database
      uri: sqlite3://./.kanthor/database.sqlite
      source: file://./migration/database/sql
    - name: datastore
      uri: sqlite3://./.kanthor/datastore.sqlite
      source: file://./migration/datastore/sql

controlplane:
  grpc:
    addr: ":8080"
  authenticator:
    engine: access_secret_key
    access_secret_key:
      access_key: kanthor_administrator_account
      secret_key: a_long_long_secret_key_that_is_hard_to_exploited
  enforcer:
    engine: casbin
    casbin:
      model_source: file://./data/enforcer/casbin_rbac_model.conf
      policy_source: file://./data/enforcer/casbin_rbac_policy.csv
  metrics:
    enable: false
    namespace: kanthor
    exporter:
      addr: ":9090"

dataplane:
  grpc:
    addr: ":8180"
  authenticator:
    engine: access_secret_key
    access_secret_key:
      access_key: kanthor_data_account
      secret_key: a_random_key_that_could_not_be_predicted
  metrics:
    enable: false
    namespace: kanthor
    exporter:
      addr: ":9190"

scheduler:
  subscriber:
    topic: schedule
    group: default
    filter_subject: kanthor.default.msg.>
    temporary: true
    max_deliver: 1
  request:
    arrange:
      concurrency: 100
  metrics:
    enable: false
    namespace: kanthor
    exporter:
      addr: ":9290"

dispatcher:
  subscriber:
    topic: dispatch
    group: default
    filter_subject: kanthor.default.req.>
    temporary: true
    max_deliver: 1
  sender:
    timeout: 1500
    retry:
      count: 1
      wait_time: 100
      wait_time_max: 2000
  circuit_breaker:
    half_open_max_pass_through_requests: 5
    half_open_trigger_minimum_requests: 10
    half_open_trigger_error_threshold_ratio: 0.1
    close_state_clear_interval: 600000
    open_state_duration: 300000
  metrics:
    enable: false
    namespace: kanthor
    exporter:
      addr: ":9390"