tier: default

logger:
  pretty: true
  level: debug
  with:
    env: localhost

cryptography:
  kdf: {}
  symmetric:
    key: b16142af34f3235bf221f1f620bf59d1 # md5 hash of kanthor_root_key

sender:
  trace: true
  timeout: 10000 # 10s
  retry:
    count: 1
    wait_time: 5000 # 5s
    
idempotency:
  namespace: kanthor.idempotency
  uri: redis://127.0.0.1:6379/0
  time_to_live: 86400000 # 1 day

circuit_breaker:
  close:
    cleanup_interval: 600000 # 10m
  half:
    passthrough_requests: 10
  open:
    duration: 1800000 # 30m
    conditions:
      error_consecutive: 10
      error_ratio: 0.5

distributed_lock_manager:
  namespace: kanthor.dlm
  uri: redis://127.0.0.1:6379/0
  time_to_live: 3600000 # 1h

authorizator:
  engine: casbin
  casbin:
    model_uri: file://./data/authorizator/casbin_rbac_model.conf
    policy_uri: postgres://postgres:changemenow@127.0.0.1/postgres?connect_timeout=30&application_name=kanthor.authorizator
    policy_namespace: kanthor_authz

cache:
  namespace: kanthor.cache
  uri: redis://127.0.0.1:6379/0
  time_to_live: 3600000 # 1h

metric:
  engine: otel
  otel:
    endpoint: localhost:4317
    interval: 15000
    labels:
      env: localhost

database:
  uri: postgres://postgres:changemenow@127.0.0.1/postgres?connect_timeout=30&application_name=kanthor.database
  migration:
    source: file://./migration/database/sql

datastore:
  uri: postgres://postgres:changemenow@127.0.0.1/postgres?connect_timeout=30&application_name=kanthor.datastore
  migration:
    source: file://./migration/datastore/sql

stream:
  uri: nats://127.0.0.1:4222
  nats:
    replicas: 0
    limits:
      msg_bytes: 32000
      msgs: 1000000
      bytes: 3200000000
      # 60*60*24*3 = 3d
      age: 259200
  publisher:
    routine_concurrency: 1000
    routines_timeout: 60000 # 60s
  subscriber:
    max_retry: 1
    routine_concurrency: 1000
    routines_timeout: 60000 # 60s

# application services
sdkapi:
  gateway:
    engine: httpx
    httpx:
      addr: :8180

portalapi:
  gateway:
    engine: httpx
    httpx:
      addr: :8280
  authenticator:
    engine: ask
    ask:
      access_key: kanthor_root_key
      secret_key: kanthor_root_password
      # base64(access_key:secret_key): a2FudGhvcl9yb290X2tleTprYW50aG9yX3Jvb3RfcGFzc3dvcmQ=
      
scheduler:
  subscriber:
    name: scheduler
    max_retry: 3
    max_waiting: 100
    max_ack_pending: 100000
    max_ack_wating_duration: 15000
    max_request_batch: 1000
  request:
    schedule:
      routine_concurrency: 500
      routines_timeout: 60000

dispatcher:
  subscriber:
    name: dispatcher
    max_retry: 3
    max_waiting: 100
    max_ack_pending: 100000
    max_ack_wating_duration: 15000
    max_request_batch: 1000
  forwarder:
    send:
      routine_concurrency: 300
      routines_timeout: 60000

storage:
  subscriber:
    name: storage
    max_retry: 3
    max_waiting: 100
    max_ack_pending: 100000
    max_ack_wating_duration: 15000
    max_request_batch: 1000
  warehouse:
    put:
      routine_concurrency: 3
      routines_timeout: 60000

attempt:
  trigger:
    subscriber:
      name: attempt_trigger
      max_retry: 3
      max_waiting: 100
      max_ack_pending: 100000
      max_ack_wating_duration: 15000
      max_request_batch: 1000
    planner:
      schedule: "*/15 * * * *"
      routines_timeout: 60000
      scan_size: 999999
      scan_start: -324000 # 1h30m
      scan_end: -1800000 # 30m
    executor:
      routine_concurrency: 3
      routines_timeout: 60000
      attempt_delay: 1800000 # 30m
