logger:
  pretty: true
  level: debug

bucket:
  layout: "20060102"

streaming:
  uri: nats://127.0.0.1:4222
  stream:
    name: default
    subjects:
      - kanthor.default.>
    replicas: 0
    limits:
      msgs: 50000
      msg_bytes: 65536
      # 64kb * 50000 ~ 3Gb
      bytes: 3276800000
      # 60*60*24*3 = 3d
      age: 259200

database:
  uri: sqlite3://./.kanthor/database.sqlite

datastore:
  uri: sqlite3://./.kanthor/datastore.sqlite

migration:
  source: file://./migration/scripts/sql

dataplane:
  grpc:
    addr: ":8081"

scheduler:
  consumer:
    topic: schedule
    group: default
    filter_subject: kanthor.default.msg.>
    temporary: true
    max_deliver: 1

dispatcher:
  consumer:
    topic: dispatch
    group: default
    filter_subject: kanthor.default.req.>
    temporary: true
    max_deliver: 1