# refs
redis_uri: &redis_uri redis://127.0.0.1:6379/0
postgres_uri: &postgres_uri postgres://postgres:changemenow@127.0.0.1/postgres?connect_timeout=30&sslmode=disable
nats_uri: &nats_uri nats://127.0.0.1:4222

logger:
  pretty: true
  level: debug
  with:
    env: localhost

database:
  uri: *postgres_uri
  migration:
    source: file://./data/migration/database/sql

datastore:
  uri: *postgres_uri
  migration:
    source: file://./data/migration/datastore/sql
 
# infrastructure
infrastructure:
  cryptography:
    kdf: {}
    symmetric:
      key: b16142af34f3235bf221f1f620bf59d1 # md5 hash of kanthor_root_key

  sender:
    trace: true
    timeout: 10000 # 10s
    retry:
      count: 1
      wait_time: 5000 # 5s
      
  circuit_breaker:
    close:
      cleanup_interval: 600000 # 10m
    half:
      passthrough_requests: 10
    open:
      duration: 1800000 # 30m
      conditions:
        error_consecutive: 10
        error_ratio: 0.5

  idempotency:
    uri: *redis_uri
    time_to_live: 300000 # 5m

  distributed_lock_manager:
    uri: *redis_uri
    timeout: 60000 # 1m

  cache:
    uri: *redis_uri
    time_to_live: 43200000 # 12h

  authorizator:
    engine: casbin
    casbin:
      model_uri: file://./data/authorizator/casbin_rbac_model.conf
      policy_uri: *postgres_uri
      watcher: 
        uri: *nats_uri

  metric:
    engine: noop

  streaming:
    name: main
    uri: *nats_uri
    nats:
      replicas: 0
      limits:
        msg_bytes: 32000
        msgs: 1000000
        bytes: 32000000000
        age: 259200000 #3d
    publisher:
      timeout: 30000 # 30s
      rate_limit: 300
    subscriber:
      max_retry: 1
      timeout: 60000 # 60s
      concurrency: 1000
      throughput: 30000

# services
sdk:
  gateway:
    addr: :8180
    timeout: 60000
  # the sdk has internal authenticator

portal:
  gateway:
    addr: :8280
    timeout: 60000
  authenticator:
    engine: ask
    ask:
      access_key: kanthor_root_key
      secret_key: kanthor_root_password
      # base64(access_key:secret_key): a2FudGhvcl9yb290X2tleTprYW50aG9yX3Jvb3RfcGFzc3dvcmQ=
      
scheduler:
  request:
    schedule:
      timeout: 60000 # 60s

dispatcher:
  forwarder:
    send:
      concurrency: 500

storage:
  warehouse:
    put:
      timeout: 60000 # 60s
      size: 1000

attempt:
  trigger:
    planner:
      schedule: "*/15 * * * *"
      timeout: 60000 # 60s
      scan_start: -86400000 # 24h
      scan_end: -1800000 # 30m
      size: 500
    executor:
      timeout: 60000 # 60s
      concurrency: 500
      arrange_delay: 1800000 # 30m
  endeavor:
    planner:
      schedule: "*/5 * * * *"
      timeout: 60000 # 60s
      scan_start: -86400000 # 24h
      scan_end: -1800000 # 30m
    executor:
      timeout: 60000 # 60s
      concurrency: 500
      reschedule_delay: 1800000 # 30m
