# shares
streaming: &streaming
  uri: nats://127.0.0.1:4222
  stream:
    name: default
    subjects:
      - kanthor.default.msg.>
      - kanthor.default.req.>
      - kanthor.default.res.>
    replicas: 0
    limits:
      msgs: 50000
      msg_bytes: 65536
      # 64kb * 50000 ~ 3Gb
      bytes: 3500000000
      # 60*60*24*3 = 3d
      age: 259200

cache: &cache
  uri: redis://127.0.0.1:6379/0
  time_to_live: 3600000 # 1 hour

logger:
  pretty: true
  level: debug
  with:
    environment: localhost

bucket:
  layout: "20060102"

cryptography:
  kdf: {}
  symmetric:
    key: b16142af34f3235bf221f1f620bf59d1 # md5 hash of kanthor_root_key

idempotency:
  namespace: idempotency
  uri: redis://127.0.0.1:6379/0
  time_to_live: 86400000 # 1 day

coordinator:
  engine: nats
  nats:
    uri: nats://127.0.0.1:4222
    subject: kanthor.coordinator

database:
  uri: postgres://postgres:changemenow@127.0.0.1/postgres?connect_timeout=30&application_name=kanthor.database

datastore:
  uri: postgres://postgres:changemenow@127.0.0.1/postgres?connect_timeout=30&application_name=kanthor.datastore

# services
migration:
  tasks:
    - name: database
      uri: postgres://postgres:changemenow@127.0.0.1/postgres?connect_timeout=30&application_name=kanthor.database
      source: file://./migration/database/sql
    - name: datastore
      uri: postgres://postgres:changemenow@127.0.0.1/postgres?connect_timeout=30&application_name=kanthor.datastore
      source: file://./migration/datastore/sql

sdkapi:
  cache: *cache
  portal_connection:
    account: http://localhost:8180/api/account/me
  gateway:
    engine: httpx
    httpx:
      addr: :8080
  authorizator:
    engine: casbin
    casbin:
      model_uri: file://./data/authorizator/casbin_rbac_model.conf
      policy_uri: postgres://postgres:changemenow@127.0.0.1/postgres?connect_timeout=30&application_name=kanthor.services.sdk
      policy_namespace: sdk
  publisher:
    connection: *streaming
  metrics:
    engine: prometheus
    prometheus:
      labels:
        service: sdkapi

portalapi:
  cache: *cache
  gateway:
    engine: httpx
    httpx:
      addr: :8180
  authenticator:
    engine: ask
    ask:
      access_key: kanthor_root_key
      secret_key: kanthor_root_password
      # base64(access_key:secret_key): a2FudGhvcl9yb290X2tleTprYW50aG9yX3Jvb3RfcGFzc3dvcmQ=
  authorizator:
    engine: casbin
    casbin:
      model_uri: file://./data/authorizator/casbin_rbac_model.conf
      policy_uri: postgres://postgres:changemenow@127.0.0.1/postgres?connect_timeout=30&application_name=kanthor.services.portal
      policy_namespace: portal
  metrics:
    engine: prometheus
    prometheus:
      labels:
        service: portalapi

scheduler:
  cache: *cache
  publisher:
    connection: *streaming
  subscriber:
    connection: *streaming
    based_model: push
    push:
      deliver_subject: schedule
      deliver_group: default
      temporary: true
    name: schedule_default
    filter_subject: kanthor.default.msg.>
    max_deliver: 1
  request:
    arrange:
      concurrency: 100

dispatcher:
  cache: *cache
  publisher:
    connection: *streaming
  subscriber:
    connection: *streaming
    based_model: push
    push:
      deliver_subject: dispatch
      deliver_group: default
      temporary: true
    name: dispatch_default
    filter_subject: kanthor.default.req.>
    max_deliver: 1
  sender:
    timeout: 3000
    retry:
      count: 1
      wait_time: 100
      wait_time_max: 5000
  circuit_breaker:
    half_open_max_pass_through_requests: 5
    half_open_trigger_minimum_requests: 10
    half_open_trigger_error_threshold_ratio: 0.1
    close_state_clear_interval: 600000
    open_state_duration: 300000

storage:
  subscriber:
    connection: *streaming
    based_model: pull
    pull:
      max_waiting: 100
      max_ack_pending: 1000
      max_request_batch: 10
    name: storage_default
    filter_subject: kanthor.default.>
    max_deliver: 1