version: "3.8"

services:
  streaming:
    container_name: kanthor-streaming
    image: nats:2.9
    restart: unless-stopped
    networks:
      - kanthor
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "-D -js --http_port 8222"

  warehouse:
    container_name: kanthor-warehouse
    image: postgres:13-alpine
    restart: unless-stopped
    networks:
      - kanthor
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changemenow
    user: postgres
    healthcheck:
      test: [ "CMD", "pg_isready" , "-U", "postgres" ]
      interval: 8s
      timeout: 4s
      retries: 16

  cache:
    container_name: kanthor-cache
    image: redis:6-alpine
    restart: unless-stopped
    networks:
      - kanthor
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 4s
      retries: 16

  migration-database:
    image: scrapnode/kanthor:latest
    depends_on:
      warehouse:
        condition: service_healthy
    container_name: kanthor-services-migration-database
    restart: on-failure
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command: 
      - kanthor
      - migrate
      - database
      - up

  migration-datastore:
    image: scrapnode/kanthor:latest
    depends_on:
      warehouse:
        condition: service_healthy
      migration-database:
        condition: service_started
    container_name: kanthor-services-migration-datastore
    restart: on-failure
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command: 
      - kanthor
      - migrate
      - datastore
      - up

  sdk:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      cache:
        condition: service_healthy
      migration-database:
        condition: service_started
    container_name: kanthor-services-sdk
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    ports:
      - "8180:8180"
    command:
      - kanthor
      - serve
      - sdk

  portal:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      cache:
        condition: service_healthy
      migration-database:
        condition: service_started
    container_name: kanthor-services-portal
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    ports:
      - "8280:8280"
    command:
      - kanthor
      - serve
      - portal

  scheduler:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      cache:
        condition: service_healthy
      migration-database:
        condition: service_started
    container_name: kanthor-services-scheduler
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command:
      - kanthor
      - serve
      - scheduler

  dispatcher:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      cache:
        condition: service_healthy
      migration-database:
        condition: service_started
    container_name: kanthor-services-dispatcher
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command:
      - kanthor
      - serve
      - dispatcher

  storage:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      migration-database:
        condition: service_started
      migration-datastore:
        condition: service_started
    container_name: kanthor-services-storage
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command:
      - kanthor
      - serve
      - storage
 
  recovery-cronjob:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      migration-database:
        condition: service_started
      migration-datastore:
        condition: service_started
    container_name: kanthor-services-recovery-cronjob
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command:
      - kanthor
      - serve
      - recovery.cronjob
 
  recovery-consumer:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      migration-database:
        condition: service_started
      migration-datastore:
        condition: service_started
    container_name: kanthor-services-recovery-consumer
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command:
      - kanthor
      - serve
      - recovery.consumer
 
  attempt-cronjob:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      migration-database:
        condition: service_started
      migration-datastore:
        condition: service_started
    container_name: kanthor-services-attempt-cronjob
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command:
      - kanthor
      - serve
      - attempt.cronjob
 
  attempt-consumer:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      migration-database:
        condition: service_started
      migration-datastore:
        condition: service_started
    container_name: kanthor-services-attempt-consumer
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command:
      - kanthor
      - serve
      - attempt.consumer
 
  attempt-selector:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      migration-database:
        condition: service_started
      migration-datastore:
        condition: service_started
    container_name: kanthor-services-attempt-selector
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command:
      - kanthor
      - serve
      - attempt.selector
      
  attempt-endeavor:
    image: scrapnode/kanthor:latest
    depends_on:
      streaming:
        condition: service_started
      warehouse:
        condition: service_healthy
      migration-database:
        condition: service_started
      migration-datastore:
        condition: service_started
    container_name: kanthor-services-attempt-endeavor
    restart: unless-stopped
    environment:
      - KANTHOR_DATABASE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_DATASTORE_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_IDEMPOTENCY_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_DISTRIBUTED_LOCK_MANAGER_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_CACHE_URI=redis://cache:6379/0
      - KANTHOR_INFRASTRUCTURE_STREAMING_URI=nats://streaming:4222
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_POLICY_URI=postgres://postgres:changemenow@warehouse/postgres?connect_timeout=30&sslmode=disable
      - KANTHOR_INFRASTRUCTURE_AUTHORIZATOR_CASBIN_WATCHER_URI=nats://streaming:4222
    networks:
      - kanthor
    command:
      - kanthor
      - serve
      - attempt.endeavor
      
  console:
    image: scrapnode/kanthor-console:localhost
    depends_on:
      sdk:
        condition: service_started
      portal:
        condition: service_started
    container_name: kanthor-services-console
    restart: unless-stopped
    networks:
      - kanthor
    ports:
      - "9082:80"
      
  playground:
    image: scrapnode/kanthor-playground:latest
    depends_on:
      sdk:
        condition: service_started
      portal:
        condition: service_started
    container_name: kanthor-services-playground
    restart: unless-stopped
    environment:
      - KANTHOR_SDK_HOST=sdk:8180
      - KANTHOR_SDK_ENDPOINT_PUBLIC=http://localhost:8180/api
      - KANTHOR_PLAYGROUND_ENDPOINT=http://playground:9081
      - KANTHOR_PORTAL_ENDPOINT=http://portal:8280/api
      - KANTHOR_PORTAL_CREDENTIALS=YWRtaW5Aa2FudGhvcmxhYnMuY29tOmNoYW5nZW1lbm93
    networks:
      - kanthor
    ports:
      - "9081:9081"

networks:
  kanthor:
    name: kanthor