version: "3.8"

services:
  httpbin:
    image: kong/httpbin:0.1.0
    container_name: kanthor-debugging-httpbin
    ports:
      - "10080:80"
    networks:
      - kanthor

networks:
  kanthor:
    name: kanthor
    external: true