version: "3.8"

services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.84.0
    container_name: kanthor-monitoring-collector
    restart: unless-stopped
    command: [ "--config=/etc/otel/config.yaml"]
    volumes:
      - ./docker/otel:/etc/otel
    ports:
      - "4317:4317"       # OTLP over gRPC receiver
      - "4318:4318"       # OTLP over HTTP receiver
      - "9464:9464"       # Prometheus exporter
      - "8888:8888"       # metrics endpoint
      - "13133:13133"     # health check
    networks:
      - kanthor

networks:
  kanthor:
    name: kanthor
    external: true