services:
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.0.1
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

networks:
  kanthor:
    name: kanthor
    external: true