services:
  streaming:
    networks:
      - kanthor
    image: nats:2.9
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "-D -js --http_port 8222"

networks:
  kanthor:
    name: kanthor