// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/scrapnode/kanthor/config"
	"github.com/scrapnode/kanthor/infrastructure/cache"
	"github.com/scrapnode/kanthor/infrastructure/circuitbreaker"
	"github.com/scrapnode/kanthor/infrastructure/cryptography"
	"github.com/scrapnode/kanthor/infrastructure/logging"
	"github.com/scrapnode/kanthor/infrastructure/monitoring/metric"
	"github.com/scrapnode/kanthor/infrastructure/streaming"
	"github.com/scrapnode/kanthor/pkg/sender"
	"github.com/scrapnode/kanthor/pkg/timer"
	"github.com/scrapnode/kanthor/services"
	"github.com/scrapnode/kanthor/services/dispatcher"
	"github.com/scrapnode/kanthor/services/scheduler"
	"github.com/scrapnode/kanthor/usecases"
	"github.com/scrapnode/kanthor/usecases/portal"
	"github.com/scrapnode/kanthor/usecases/portal/repos"
	repos2 "github.com/scrapnode/kanthor/usecases/scheduler/repos"
)

// Injectors from wire_dispatcher.go:

func InitializeDispatcher(conf *config.Config, logger logging.Logger) (services.Service, error) {
	subscriberConfig := ResolveDispatcherSubscriberConfig(conf)
	subscriber, err := streaming.NewSubscriber(subscriberConfig, logger)
	if err != nil {
		return nil, err
	}
	timerTimer := timer.New()
	publisherConfig := ResolveDispatcherPublisherConfig(conf)
	publisher, err := streaming.NewPublisher(publisherConfig, logger)
	if err != nil {
		return nil, err
	}
	senderConfig := ResolveDispatcherSenderConfig(conf, logger)
	send := sender.New(senderConfig, logger)
	cacheConfig := ResolveDispatcherCacheConfig(conf)
	cacheCache, err := cache.New(cacheConfig, logger)
	if err != nil {
		return nil, err
	}
	circuitbreakerConfig := ResolveDispatcherCircuitBreakerConfig(conf)
	circuitBreaker, err := circuitbreaker.New(circuitbreakerConfig, logger)
	if err != nil {
		return nil, err
	}
	metricConfig := ResolveDispatcherMetricConfig(conf)
	meter := metric.New(metricConfig)
	dispatcherDispatcher := usecases.NewDispatcher(conf, logger, timerTimer, publisher, send, cacheCache, circuitBreaker, meter)
	service := dispatcher.New(conf, logger, subscriber, dispatcherDispatcher, meter)
	return service, nil
}

// Injectors from wire_portal.go:

func InitializePortalUsecase(conf *config.Config, logger logging.Logger) (portal.Portal, error) {
	cryptographyConfig := &conf.Cryptography
	cryptographyCryptography, err := cryptography.New(cryptographyConfig)
	if err != nil {
		return nil, err
	}
	timerTimer := timer.New()
	cacheConfig := ResolvePortalCacheConfig(conf)
	cacheCache, err := cache.New(cacheConfig, logger)
	if err != nil {
		return nil, err
	}
	metricConfig := ResolvePortalMetricConfig(conf)
	meter := metric.New(metricConfig)
	databaseConfig := &conf.Database
	repositories := repos.New(databaseConfig, logger, timerTimer)
	portalPortal := usecases.NewPortal(conf, logger, cryptographyCryptography, timerTimer, cacheCache, meter, repositories)
	return portalPortal, nil
}

// Injectors from wire_scheduler.go:

func InitializeScheduler(conf *config.Config, logger logging.Logger) (services.Service, error) {
	subscriberConfig := ResolveSchedulerSubscriberConfig(conf)
	subscriber, err := streaming.NewSubscriber(subscriberConfig, logger)
	if err != nil {
		return nil, err
	}
	timerTimer := timer.New()
	publisherConfig := ResolveSchedulerPublisherConfig(conf)
	publisher, err := streaming.NewPublisher(publisherConfig, logger)
	if err != nil {
		return nil, err
	}
	cacheConfig := ResolveSchedulerCacheConfig(conf)
	cacheCache, err := cache.New(cacheConfig, logger)
	if err != nil {
		return nil, err
	}
	metricConfig := ResolveSchedulerMetricConfig(conf)
	meter := metric.New(metricConfig)
	databaseConfig := &conf.Database
	repositories := repos2.New(databaseConfig, logger, timerTimer)
	schedulerScheduler := usecases.NewScheduler(conf, logger, timerTimer, publisher, cacheCache, meter, repositories)
	service := scheduler.New(conf, logger, subscriber, schedulerScheduler, meter)
	return service, nil
}

// wire_dispatcher.go:

func ResolveDispatcherPublisherConfig(conf *config.Config) *streaming.PublisherConfig {
	return &conf.Scheduler.Publisher
}

func ResolveDispatcherSubscriberConfig(conf *config.Config) *streaming.SubscriberConfig {
	return &conf.Dispatcher.Subscriber
}

func ResolveDispatcherCacheConfig(conf *config.Config) *cache.Config {
	return &conf.Dispatcher.Cache
}

func ResolveDispatcherCircuitBreakerConfig(conf *config.Config) *circuitbreaker.Config {
	return &conf.Dispatcher.CircuitBreaker
}

func ResolveDispatcherMetricConfig(conf *config.Config) *metric.Config {
	return &conf.Dispatcher.Metrics
}

func ResolveDispatcherSenderConfig(conf *config.Config, logger logging.Logger) *sender.Config {
	return &conf.Dispatcher.Sender
}

// wire_portal.go:

func ResolvePortalCacheConfig(conf *config.Config) *cache.Config {
	return &conf.Portal.Cache
}

func ResolvePortalMetricConfig(conf *config.Config) *metric.Config {
	return &conf.Portal.Metrics
}

// wire_scheduler.go:

func ResolveSchedulerPublisherConfig(conf *config.Config) *streaming.PublisherConfig {
	return &conf.Scheduler.Publisher
}

func ResolveSchedulerSubscriberConfig(conf *config.Config) *streaming.SubscriberConfig {
	return &conf.Scheduler.Subscriber
}

func ResolveSchedulerCacheConfig(conf *config.Config) *cache.Config {
	return &conf.Scheduler.Cache
}

func ResolveSchedulerMetricConfig(conf *config.Config) *metric.Config {
	return &conf.Scheduler.Metrics
}
