// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/scrapnode/kanthor/config"
	"github.com/scrapnode/kanthor/domain/repositories"
	"github.com/scrapnode/kanthor/infrastructure/database"
	"github.com/scrapnode/kanthor/infrastructure/logging"
	"github.com/scrapnode/kanthor/infrastructure/streaming"
	"github.com/scrapnode/kanthor/pkg/sender"
	"github.com/scrapnode/kanthor/pkg/timer"
	"github.com/scrapnode/kanthor/services"
	"github.com/scrapnode/kanthor/services/dataplane"
	"github.com/scrapnode/kanthor/services/dispatcher"
	"github.com/scrapnode/kanthor/services/migration"
	"github.com/scrapnode/kanthor/services/scheduler"
	"github.com/scrapnode/kanthor/usecases"
)

// Injectors from wire.go:

func InitializeMigration(conf *config.Config, logger logging.Logger) (services.Service, error) {
	databaseConfig := ResolveDatabaseConfig(conf)
	databaseDatabase := database.New(databaseConfig, logger)
	service := migration.New(conf, logger, databaseDatabase)
	return service, nil
}

func InitializeDataplane(conf *config.Config, logger logging.Logger) (services.Service, error) {
	timerTimer := timer.New()
	publisherConfig := ResolvePublisherConfig(conf)
	publisher := streaming.NewPublisher(publisherConfig, logger)
	databaseConfig := ResolveDatabaseConfig(conf)
	repositoriesRepositories := repositories.New(databaseConfig, logger, timerTimer)
	dataplaneDataplane := usecases.NewDataplane(conf, logger, timerTimer, publisher, repositoriesRepositories)
	service := dataplane.New(conf, logger, dataplaneDataplane)
	return service, nil
}

func InitializeScheduler(conf *config.Config, logger logging.Logger) (services.Service, error) {
	subscriberConfig := ResolveSchedulerSubscriberConfig(conf)
	subscriber := streaming.NewSubscriber(subscriberConfig, logger)
	timerTimer := timer.New()
	publisherConfig := ResolvePublisherConfig(conf)
	publisher := streaming.NewPublisher(publisherConfig, logger)
	databaseConfig := ResolveDatabaseConfig(conf)
	repositoriesRepositories := repositories.New(databaseConfig, logger, timerTimer)
	schedulerScheduler := usecases.NewScheduler(conf, logger, timerTimer, publisher, repositoriesRepositories)
	service := scheduler.New(conf, logger, subscriber, schedulerScheduler)
	return service, nil
}

func InitializeDispatcher(conf *config.Config, logger logging.Logger) (services.Service, error) {
	subscriberConfig := ResolveDispatcherSubscriberConfig(conf)
	subscriber := streaming.NewSubscriber(subscriberConfig, logger)
	timerTimer := timer.New()
	publisherConfig := ResolvePublisherConfig(conf)
	publisher := streaming.NewPublisher(publisherConfig, logger)
	databaseConfig := ResolveDatabaseConfig(conf)
	repositoriesRepositories := repositories.New(databaseConfig, logger, timerTimer)
	send := ResolveSender(conf, logger)
	dispatcherDispatcher := usecases.NewDispatcher(conf, logger, timerTimer, publisher, repositoriesRepositories, send)
	service := dispatcher.New(conf, logger, subscriber, dispatcherDispatcher)
	return service, nil
}

// wire.go:

func ResolvePublisherConfig(conf *config.Config) *streaming.PublisherConfig {
	return &streaming.PublisherConfig{ConnectionConfig: conf.Streaming}
}

func ResolveSchedulerSubscriberConfig(conf *config.Config) *streaming.SubscriberConfig {
	return &conf.Scheduler.Consumer
}

func ResolveDispatcherSubscriberConfig(conf *config.Config) *streaming.SubscriberConfig {
	return &conf.Dispatcher.Consumer
}

func ResolveDatabaseConfig(conf *config.Config) *database.Config {
	return &conf.Database
}

func ResolveSender(conf *config.Config, logger logging.Logger) sender.Send {
	return sender.New(&conf.Dispatcher.Sender, logger)
}
