// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/scrapnode/kanthor/config"
	"github.com/scrapnode/kanthor/infrastructure"
	"github.com/scrapnode/kanthor/infrastructure/authenticator"
	"github.com/scrapnode/kanthor/infrastructure/logging"
	"github.com/scrapnode/kanthor/infrastructure/streaming"
	"github.com/scrapnode/kanthor/pkg/sender"
	"github.com/scrapnode/kanthor/services"
	"github.com/scrapnode/kanthor/services/dispatcher"
	"github.com/scrapnode/kanthor/services/portalapi"
	"github.com/scrapnode/kanthor/services/scheduler"
	"github.com/scrapnode/kanthor/services/sdkapi"
	"github.com/scrapnode/kanthor/services/storage"
	dispatcher2 "github.com/scrapnode/kanthor/usecases/dispatcher"
	"github.com/scrapnode/kanthor/usecases/portal"
	"github.com/scrapnode/kanthor/usecases/portal/repos"
	scheduler2 "github.com/scrapnode/kanthor/usecases/scheduler"
	repos2 "github.com/scrapnode/kanthor/usecases/scheduler/repos"
	"github.com/scrapnode/kanthor/usecases/sdk"
	repos3 "github.com/scrapnode/kanthor/usecases/sdk/repos"
	storage2 "github.com/scrapnode/kanthor/usecases/storage"
	repos4 "github.com/scrapnode/kanthor/usecases/storage/repos"
)

// Injectors from wire_dispatcher.go:

func InitializeDispatcher(conf *config.Config, logger logging.Logger) (services.Service, error) {
	subscriberConfig := ResolveDispatcherSubscriberConfig(conf)
	subscriber, err := streaming.NewSubscriber(subscriberConfig, logger)
	if err != nil {
		return nil, err
	}
	infrastructureInfrastructure, err := infrastructure.New(conf, logger)
	if err != nil {
		return nil, err
	}
	dispatcherDispatcher, err := InitializeDispatcherUsecase(conf, logger, infrastructureInfrastructure)
	if err != nil {
		return nil, err
	}
	service := dispatcher.New(conf, logger, subscriber, infrastructureInfrastructure, dispatcherDispatcher)
	return service, nil
}

func InitializeDispatcherUsecase(conf *config.Config, logger logging.Logger, infra *infrastructure.Infrastructure) (dispatcher2.Dispatcher, error) {
	publisherConfig := ResolveDispatcherPublisherConfig(conf)
	publisher, err := streaming.NewPublisher(publisherConfig, logger)
	if err != nil {
		return nil, err
	}
	senderConfig := ResolveDispatcherSenderConfig(conf, logger)
	send := sender.New(senderConfig, logger)
	dispatcherDispatcher := dispatcher2.New(conf, logger, infra, publisher, send)
	return dispatcherDispatcher, nil
}

// Injectors from wire_portal_api.go:

func InitializePortalApi(conf *config.Config, logger logging.Logger) (services.Service, error) {
	infrastructureInfrastructure, err := infrastructure.New(conf, logger)
	if err != nil {
		return nil, err
	}
	authenticatorConfig := ResolvePortalApiAuthenticatorConfig(conf)
	authenticatorAuthenticator, err := authenticator.New(authenticatorConfig, logger)
	if err != nil {
		return nil, err
	}
	portal, err := InitializePortalUsecase(conf, logger, infrastructureInfrastructure)
	if err != nil {
		return nil, err
	}
	service := portalapi.New(conf, logger, infrastructureInfrastructure, authenticatorAuthenticator, portal)
	return service, nil
}

func InitializePortalUsecase(conf *config.Config, logger logging.Logger, infra *infrastructure.Infrastructure) (portal.Portal, error) {
	databaseConfig := &conf.Database
	repositories := repos.New(databaseConfig, logger)
	portalPortal := portal.New(conf, logger, infra, repositories)
	return portalPortal, nil
}

// Injectors from wire_scheduler.go:

func InitializeScheduler(conf *config.Config, logger logging.Logger) (services.Service, error) {
	subscriberConfig := ResolveSchedulerSubscriberConfig(conf)
	subscriber, err := streaming.NewSubscriber(subscriberConfig, logger)
	if err != nil {
		return nil, err
	}
	infrastructureInfrastructure, err := infrastructure.New(conf, logger)
	if err != nil {
		return nil, err
	}
	schedulerScheduler, err := InitializeSchedulerUsecase(conf, logger, infrastructureInfrastructure)
	if err != nil {
		return nil, err
	}
	service := scheduler.New(conf, logger, subscriber, infrastructureInfrastructure, schedulerScheduler)
	return service, nil
}

func InitializeSchedulerUsecase(conf *config.Config, logger logging.Logger, infra *infrastructure.Infrastructure) (scheduler2.Scheduler, error) {
	publisherConfig := ResolveSchedulerPublisherConfig(conf)
	publisher, err := streaming.NewPublisher(publisherConfig, logger)
	if err != nil {
		return nil, err
	}
	databaseConfig := &conf.Database
	repositories := repos2.New(databaseConfig, logger)
	schedulerScheduler := scheduler2.New(conf, logger, infra, publisher, repositories)
	return schedulerScheduler, nil
}

// Injectors from wire_sdk_api.go:

func InitializeSdkApi(conf *config.Config, logger logging.Logger) (services.Service, error) {
	infrastructureInfrastructure, err := infrastructure.New(conf, logger)
	if err != nil {
		return nil, err
	}
	sdk, err := InitializeSdkUsecase(conf, logger, infrastructureInfrastructure)
	if err != nil {
		return nil, err
	}
	service := sdkapi.New(conf, logger, infrastructureInfrastructure, sdk)
	return service, nil
}

func InitializeSdkUsecase(conf *config.Config, logger logging.Logger, infra *infrastructure.Infrastructure) (sdk.Sdk, error) {
	publisherConfig := ResolveSdkApiPublisherConfig(conf)
	publisher, err := streaming.NewPublisher(publisherConfig, logger)
	if err != nil {
		return nil, err
	}
	databaseConfig := &conf.Database
	repositories := repos3.New(databaseConfig, logger)
	sdkSdk := sdk.New(conf, logger, infra, publisher, repositories)
	return sdkSdk, nil
}

// Injectors from wire_storage.go:

func InitializeStorage(conf *config.Config, logger logging.Logger) (services.Service, error) {
	infrastructureInfrastructure, err := infrastructure.New(conf, logger)
	if err != nil {
		return nil, err
	}
	subscriberConfig := ResolveStorageSubscriberConfig(conf)
	subscriber, err := streaming.NewSubscriber(subscriberConfig, logger)
	if err != nil {
		return nil, err
	}
	storageStorage, err := InitializeStorageUsecase(conf, logger, infrastructureInfrastructure)
	if err != nil {
		return nil, err
	}
	service := storage.New(conf, logger, infrastructureInfrastructure, subscriber, storageStorage)
	return service, nil
}

func InitializeStorageUsecase(conf *config.Config, logger logging.Logger, infra *infrastructure.Infrastructure) (storage2.Storage, error) {
	datastoreConfig := &conf.Datastore
	repositories := repos4.New(datastoreConfig, logger)
	storageStorage := storage2.New(conf, logger, infra, repositories)
	return storageStorage, nil
}

// wire_dispatcher.go:

func ResolveDispatcherPublisherConfig(conf *config.Config) *streaming.PublisherConfig {
	return &conf.Scheduler.Publisher
}

func ResolveDispatcherSubscriberConfig(conf *config.Config) *streaming.SubscriberConfig {
	return &conf.Dispatcher.Subscriber
}

func ResolveDispatcherSenderConfig(conf *config.Config, logger logging.Logger) *sender.Config {
	return &conf.Dispatcher.Sender
}

// wire_portal_api.go:

func ResolvePortalApiAuthenticatorConfig(conf *config.Config) *authenticator.Config {
	return &conf.PortalApi.Authenticator
}

// wire_scheduler.go:

func ResolveSchedulerPublisherConfig(conf *config.Config) *streaming.PublisherConfig {
	return &conf.Scheduler.Publisher
}

func ResolveSchedulerSubscriberConfig(conf *config.Config) *streaming.SubscriberConfig {
	return &conf.Scheduler.Subscriber
}

// wire_sdk_api.go:

func ResolveSdkApiPublisherConfig(conf *config.Config) *streaming.PublisherConfig {
	return &conf.SdkApi.Publisher
}

// wire_storage.go:

func ResolveStorageSubscriberConfig(conf *config.Config) *streaming.SubscriberConfig {
	return &conf.Storage.Subscriber
}
