receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

processors:
  batch:
    send_batch_size: 300
    timeout: 15s

exporters:
  # Data sources: traces, metrics, logs
  logging:
    loglevel: debug

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  extensions:
    - health_check
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
