CREATE TABLE IF NOT EXISTS workspace
(
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0,
    deleted_at  BIGINT NOT NULL DEFAULT 0,

    owner_id VARCHAR(64) NOT NULL,
    name VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS workspace_tier
(
    workspace_id VARCHAR(64) NOT NULL,
    name VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS application
(
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0,
    deleted_at  BIGINT NOT NULL DEFAULT 0,

    workspace_id VARCHAR(64) NOT NULL,
    name VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS endpoint
(
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0,
    deleted_at  BIGINT NOT NULL DEFAULT 0,

    app_id VARCHAR(64) NOT NULL,
    name VARCHAR(256) NOT NULL,
    uri TEXT NOT NULL

);

CREATE TABLE IF NOT EXISTS endpoint_rule
(
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0,
    deleted_at  BIGINT NOT NULL DEFAULT 0,

    endpoint_id VARCHAR(64) NOT NULL,
    condition TEXT NOT NULL,
    priority SMALLINT NOT NULL DEFAULT 0,
    exclusionary BOOLEAN NOT NULL DEFAULT FALSE
);
