basePath: /api
consumes:
- application/json
definitions:
  authenticator.Account:
    properties:
      metadata:
        additionalProperties:
          type: string
        type: object
      name:
        type: string
      sub:
        type: string
    type: object
  authorizator.Permission:
    properties:
      action:
        type: string
      object:
        type: string
      role:
        type: string
    type: object
  entities.Workspace:
    properties:
      createdAt:
        description: |-
          I didn't find a way to disable automatic fields modify yet
          so, I use a tag to disable this feature here
          but, we should keep our entities stateless if we can
        type: integer
      id:
        type: string
      name:
        type: string
      ownerId:
        type: string
      tier:
        type: string
      updatedAt:
        type: integer
    type: object
  gateway.Error:
    properties:
      code:
        type: string
      error:
        type: string
    type: object
  rest.AccountGetRes:
    properties:
      account:
        $ref: '#/definitions/authenticator.Account'
      workspaces:
        items:
          $ref: '#/definitions/entities.Workspace'
        type: array
    type: object
  rest.AccountSetupReq:
    properties:
      workspace_name:
        type: string
    type: object
  rest.AccountSetupRes:
    properties:
      account:
        $ref: '#/definitions/authenticator.Account'
      workspace:
        $ref: '#/definitions/rest.Workspace'
    type: object
  rest.Workspace:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      owner_id:
        type: string
      tier:
        type: string
      updated_at:
        type: integer
    type: object
  rest.WorkspaceCredentials:
    properties:
      created_at:
        type: integer
      expired_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      ws_id:
        type: string
    type: object
  rest.WorkspaceCredentialsCreateReq:
    properties:
      expired_at:
        default: 1893456000000
        type: integer
      name:
        default: swagger demo
        type: string
    type: object
  rest.WorkspaceCredentialsCreateRes:
    properties:
      id:
        type: string
      name:
        type: string
      password:
        type: string
      user:
        type: string
    type: object
  rest.WorkspaceCredentialsExpireReq:
    properties:
      duration:
        default: 1800000
        type: integer
    type: object
  rest.WorkspaceCredentialsExpireRes:
    properties:
      expired_at:
        type: integer
      id:
        type: string
    type: object
  rest.WorkspaceCredentialsGetRes:
    properties:
      created_at:
        type: integer
      expired_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      ws_id:
        type: string
    type: object
  rest.WorkspaceCredentialsListRes:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/rest.WorkspaceCredentials'
        type: array
    type: object
  rest.WorkspaceCredentialsUpdateReq:
    properties:
      expired_at:
        default: 1893456000000
        type: integer
      name:
        default: swagger demo update
        type: string
    type: object
  rest.WorkspaceCredentialsUpdateRes:
    properties:
      created_at:
        type: integer
      expired_at:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
      ws_id:
        type: string
    type: object
  rest.WorkspaceGetRes:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      owner_id:
        type: string
      permissions:
        items:
          $ref: '#/definitions/authorizator.Permission'
        type: array
      tier:
        type: string
      updated_at:
        type: integer
    type: object
  rest.WorkspaceUpdateReq:
    properties:
      name:
        type: string
    type: object
  rest.WorkspaceUpdateRes:
    properties:
      created_at:
        type: integer
      id:
        type: string
      name:
        type: string
      owner_id:
        type: string
      tier:
        type: string
      updated_at:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@kanthorlabs.com
    name: Kanthor Support
    url: http://kanthorlabs.com/support
  description: Portal API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kanthorlabs.com/terms/
  title: Kanthor Portal API
  version: "1.0"
paths:
  /account/me:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.AccountGetRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - account
  /account/setup:
    post:
      parameters:
      - description: setup options
        in: body
        name: props
        required: true
        schema:
          $ref: '#/definitions/rest.AccountSetupReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.AccountSetupRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - account
  /credentials:
    get:
      parameters:
      - collectionFormat: csv
        description: list by ids
        in: query
        items:
          type: string
        name: id
        type: array
      - description: search keyword
        in: query
        name: _q
        type: string
      - default: 10
        description: limit returning records
        in: query
        name: _limit
        type: integer
      - default: 0
        description: requesting page
        in: query
        name: _page
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.WorkspaceCredentialsListRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - credentials
    post:
      parameters:
      - description: credentials properties
        in: body
        name: props
        required: true
        schema:
          $ref: '#/definitions/rest.WorkspaceCredentialsCreateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.WorkspaceCredentialsCreateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - credentials
  /credentials/{wsc_id}:
    get:
      parameters:
      - description: credentials id
        in: path
        name: wsc_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.WorkspaceCredentialsGetRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - credentials
    patch:
      parameters:
      - description: credentials id
        in: path
        name: wsc_id
        required: true
        type: string
      - description: credentials properties
        in: body
        name: props
        required: true
        schema:
          $ref: '#/definitions/rest.WorkspaceCredentialsUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.WorkspaceCredentialsUpdateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - credentials
  /credentials/{wsc_id}/expiration:
    put:
      parameters:
      - description: credentials id
        in: path
        name: wsc_id
        required: true
        type: string
      - description: credentials properties
        in: body
        name: props
        required: true
        schema:
          $ref: '#/definitions/rest.WorkspaceCredentialsExpireReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.WorkspaceCredentialsExpireRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - credentials
  /workspace:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.WorkspaceGetRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - Authorization: []
      tags:
      - workspace
  /workspace/me:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.WorkspaceGetRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - workspace
    patch:
      parameters:
      - description: credentials properties
        in: body
        name: props
        required: true
        schema:
          $ref: '#/definitions/rest.WorkspaceUpdateReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.WorkspaceUpdateRes'
        default:
          description: ""
          schema:
            $ref: '#/definitions/gateway.Error'
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - workspace
produces:
- application/json
securityDefinitions:
  Authorization:
    description: '[Bearer JWT_TOKEN] or [Basic base64(key:secret)]'
    in: header
    name: Authorization
    type: apiKey
  WorkspaceId:
    description: The selected workspace id you are working with
    in: header
    name: x-authorization-workspace
    type: apiKey
swagger: "2.0"
