// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplatePortal = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://kanthorlabs.com/terms/",
        "contact": {
            "name": "Kanthor Support",
            "url": "http://kanthorlabs.com/support",
            "email": "support@kanthorlabs.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "account"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AccountGetRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/analytics/overview": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "analytics"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AnalyticsGetOverviewRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/application/{app_id}/message": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "limit returning records",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1669914060000,
                        "description": "starting time to scan in milliseconds",
                        "name": "_start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1985533260000,
                        "description": "ending time to scan in milliseconds",
                        "name": "_end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationListMessageRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/application/{app_id}/message/{msg_id}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "application"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationGetMessageRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/credentials": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "credentials"
                ],
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "list by ids",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "_q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "limit returning records",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "requesting page",
                        "name": "_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceCredentialsListRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "credentials"
                ],
                "parameters": [
                    {
                        "description": "credentials payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkspaceCredentialsCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceCredentialsCreateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/credentials/{wsc_id}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "credentials"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "credentials id",
                        "name": "wsc_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceCredentialsGetRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "credentials"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "credentials id",
                        "name": "wsc_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "credentials payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkspaceCredentialsUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceCredentialsUpdateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/credentials/{wsc_id}/expiration": {
            "put": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "credentials"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "credentials id",
                        "name": "wsc_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "credentials payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkspaceCredentialsExpireReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceCredentialsExpireRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/endpoint/{ep_id}/message": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "endpoint"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "limit returning records",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1669914060000,
                        "description": "starting time to scan in milliseconds",
                        "name": "_start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1985533260000,
                        "description": "ending time to scan in milliseconds",
                        "name": "_end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EndpointListMessageRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/endpoint/{ep_id}/message/{msg_id}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    },
                    {
                        "WorkspaceId": []
                    }
                ],
                "tags": [
                    "endpoint"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EndpointGetMessageRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/workspace": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "workspace"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceGetRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "workspace"
                ],
                "parameters": [
                    {
                        "description": "workspace payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkspaceCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceCreateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/workspace/{ws_id}": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "workspace"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "workspace id",
                        "name": "ws_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceGetRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "workspace"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "workspace id",
                        "name": "ws_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "workspace payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkspaceUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceUpdateRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        },
        "/workspace/{ws_id}/transfer": {
            "get": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "workspace"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "workspace id",
                        "name": "ws_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceExportRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "tags": [
                    "workspace"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "workspace id",
                        "name": "ws_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "import payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkspaceImportReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkspaceImportRes"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/gateway.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AccountGetRes": {
            "type": "object",
            "required": [
                "account",
                "workspaces"
            ],
            "properties": {
                "account": {
                    "$ref": "#/definitions/authenticator.Account"
                },
                "workspaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Workspace"
                    }
                }
            }
        },
        "AnalyticsGetOverviewRes": {
            "type": "object",
            "required": [
                "application_count",
                "credentials_count",
                "endpoint_count",
                "rule_count"
            ],
            "properties": {
                "application_count": {
                    "type": "integer"
                },
                "credentials_count": {
                    "type": "integer"
                },
                "endpoint_count": {
                    "type": "integer"
                },
                "rule_count": {
                    "type": "integer"
                }
            }
        },
        "ApplicationGetMessageRes": {
            "type": "object",
            "required": [
                "app_id",
                "body",
                "headers",
                "id",
                "metadata",
                "timestamp",
                "type"
            ],
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "headers": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "ApplicationListMessageRes": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Message"
                    }
                }
            }
        },
        "EndpointGetMessageRes": {
            "type": "object",
            "required": [
                "app_id",
                "body",
                "headers",
                "id",
                "metadata",
                "request_count",
                "request_latest_ts",
                "requests",
                "response_count",
                "response_latest_ts",
                "responses",
                "success_id",
                "timestamp",
                "type"
            ],
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "headers": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "request_count": {
                    "type": "integer"
                },
                "request_latest_ts": {
                    "type": "integer"
                },
                "requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Request"
                    }
                },
                "response_count": {
                    "type": "integer"
                },
                "response_latest_ts": {
                    "type": "integer"
                },
                "responses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Response"
                    }
                },
                "success_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "EndpointListMessageRes": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/EndpointMessage"
                    }
                }
            }
        },
        "EndpointMessage": {
            "type": "object",
            "required": [
                "app_id",
                "body",
                "headers",
                "id",
                "metadata",
                "request_count",
                "request_latest_ts",
                "requests",
                "response_count",
                "response_latest_ts",
                "responses",
                "success_id",
                "timestamp",
                "type"
            ],
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "headers": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "request_count": {
                    "type": "integer"
                },
                "request_latest_ts": {
                    "type": "integer"
                },
                "requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Request"
                    }
                },
                "response_count": {
                    "type": "integer"
                },
                "response_latest_ts": {
                    "type": "integer"
                },
                "responses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Response"
                    }
                },
                "success_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "Message": {
            "type": "object",
            "required": [
                "app_id",
                "body",
                "headers",
                "id",
                "metadata",
                "timestamp",
                "type"
            ],
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "headers": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "Request": {
            "type": "object",
            "required": [
                "app_id",
                "body",
                "ep_id",
                "headers",
                "id",
                "metadata",
                "method",
                "msg_id",
                "timestamp",
                "type",
                "uri"
            ],
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "ep_id": {
                    "type": "string"
                },
                "headers": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "msg_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "Response": {
            "type": "object",
            "required": [
                "app_id",
                "body",
                "ep_id",
                "error",
                "headers",
                "id",
                "metadata",
                "msg_id",
                "req_id",
                "status",
                "timestamp",
                "type",
                "uri"
            ],
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "ep_id": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "headers": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "msg_id": {
                    "type": "string"
                },
                "req_id": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "Workspace": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "owner_id",
                "tier",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "tier": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "WorkspaceCreateReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "default": "main"
                }
            }
        },
        "WorkspaceCreateRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "owner_id",
                "tier",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "tier": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "WorkspaceCredentials": {
            "type": "object",
            "required": [
                "created_at",
                "expired_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "expired_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "ws_id": {
                    "type": "string"
                }
            }
        },
        "WorkspaceCredentialsCreateReq": {
            "type": "object",
            "required": [
                "expired_at",
                "name"
            ],
            "properties": {
                "expired_at": {
                    "type": "integer",
                    "default": 1893456000000
                },
                "name": {
                    "type": "string",
                    "default": "swagger demo"
                }
            }
        },
        "WorkspaceCredentialsCreateRes": {
            "type": "object",
            "required": [
                "id",
                "name",
                "password",
                "user"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "WorkspaceCredentialsExpireReq": {
            "type": "object",
            "required": [
                "duration"
            ],
            "properties": {
                "duration": {
                    "type": "integer",
                    "default": 1800000
                }
            }
        },
        "WorkspaceCredentialsExpireRes": {
            "type": "object",
            "required": [
                "expired_at",
                "id"
            ],
            "properties": {
                "expired_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "WorkspaceCredentialsGetRes": {
            "type": "object",
            "required": [
                "created_at",
                "expired_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "expired_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "ws_id": {
                    "type": "string"
                }
            }
        },
        "WorkspaceCredentialsListRes": {
            "type": "object",
            "required": [
                "count",
                "data"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkspaceCredentials"
                    }
                }
            }
        },
        "WorkspaceCredentialsUpdateReq": {
            "type": "object",
            "required": [
                "expired_at",
                "name"
            ],
            "properties": {
                "expired_at": {
                    "type": "integer",
                    "default": 1893456000000
                },
                "name": {
                    "type": "string",
                    "default": "swagger demo update"
                }
            }
        },
        "WorkspaceCredentialsUpdateRes": {
            "type": "object",
            "required": [
                "created_at",
                "expired_at",
                "id",
                "name",
                "updated_at",
                "ws_id"
            ],
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "expired_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "ws_id": {
                    "type": "string"
                }
            }
        },
        "WorkspaceExportRes": {
            "type": "object",
            "required": [
                "applications",
                "name"
            ],
            "properties": {
                "applications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkspaceSnapshotApp"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "WorkspaceGetRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "owner_id",
                "permissions",
                "tier",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/authorizator.Permission"
                    }
                },
                "tier": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "WorkspaceImportReq": {
            "type": "object",
            "required": [
                "snapshot"
            ],
            "properties": {
                "snapshot": {
                    "$ref": "#/definitions/WorkspaceSnapshot"
                }
            }
        },
        "WorkspaceImportRes": {
            "type": "object",
            "required": [
                "app_id",
                "ep_id",
                "epr_id"
            ],
            "properties": {
                "app_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ep_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "epr_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "WorkspaceSnapshot": {
            "type": "object",
            "required": [
                "applications",
                "name"
            ],
            "properties": {
                "applications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkspaceSnapshotApp"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "WorkspaceSnapshotApp": {
            "type": "object",
            "required": [
                "endpoints",
                "name"
            ],
            "properties": {
                "endpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkspaceSnapshotEp"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "WorkspaceSnapshotEp": {
            "type": "object",
            "required": [
                "method",
                "name",
                "rules",
                "uri"
            ],
            "properties": {
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkspaceSnapshotEpr"
                    }
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "WorkspaceSnapshotEpr": {
            "type": "object",
            "required": [
                "condition_expression",
                "condition_source",
                "exclusionary",
                "name",
                "priority"
            ],
            "properties": {
                "condition_expression": {
                    "type": "string"
                },
                "condition_source": {
                    "type": "string"
                },
                "exclusionary": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                }
            }
        },
        "WorkspaceUpdateReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "another name"
                }
            }
        },
        "WorkspaceUpdateRes": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "owner_id",
                "tier",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "tier": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "authenticator.Account": {
            "type": "object",
            "required": [
                "metadata",
                "name",
                "sub"
            ],
            "properties": {
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "sub": {
                    "type": "string"
                }
            }
        },
        "authorizator.Permission": {
            "type": "object",
            "required": [
                "action",
                "object",
                "role"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "gateway.Error": {
            "type": "object",
            "required": [
                "code",
                "error"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Authorization": {
            "description": "[Bearer JWT_TOKEN] or [Basic base64(key:secret)]",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "WorkspaceId": {
            "description": "The selected workspace id you are working with",
            "type": "apiKey",
            "name": "x-authorization-workspace",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfoPortal holds exported Swagger Info so clients can modify it
var SwaggerInfoPortal = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Kanthor Portal API",
	Description:      "Portal API",
	InfoInstanceName: "Portal",
	SwaggerTemplate:  docTemplatePortal,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoPortal.InstanceName(), SwaggerInfoPortal)
}
