/**
 * Kanthor SDK API
 * SDK API
 *
 * OpenAPI spec version: 1.0
 * Contact: support@kanthorlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RestEndpointCreateReq {
    'method': RestEndpointCreateReqMethodEnum;
    'name': string;
    'secretKey'?: string;
    'uri': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "RestEndpointCreateReqMethodEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "secretKey",
            "baseName": "secret_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RestEndpointCreateReq.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RestEndpointCreateReqMethodEnum {
    Post = 'POST',
    Put = 'PUT'
}

