/**
 * Kanthor SDK API
 * SDK API
 *
 * OpenAPI spec version: 1.0
 * Contact: support@kanthorlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuthenticatorAccount } from '../models/AuthenticatorAccount';
import { AuthorizatorPermission } from '../models/AuthorizatorPermission';
import { HttpFile } from '../http/http';

export class RestAccountGetRes {
    'account'?: AuthenticatorAccount;
    'permissions'?: Array<AuthorizatorPermission>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "AuthenticatorAccount",
            "format": ""
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<AuthorizatorPermission>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RestAccountGetRes.attributeTypeMap;
    }

    public constructor() {
    }
}

