/**
 * Kanthor SDK API
 * SDK API
 *
 * OpenAPI spec version: 1.0
 * Contact: support@kanthorlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitiesEndpointRule } from '../models/EntitiesEndpointRule';
import { HttpFile } from '../http/http';

export class RestEndpointRuleListRes {
    'cursor'?: string;
    'data'?: Array<EntitiesEndpointRule>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<EntitiesEndpointRule>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RestEndpointRuleListRes.attributeTypeMap;
    }

    public constructor() {
    }
}

