# normal
bucket:
  layout: "20060102"

# components
logger:
  pretty: true
  level: debug
  with:
    environment: localhost

streaming:
  uri: nats://streaming:4222
  stream:
    name: default
    subjects:
      - kanthor.default.>
    replicas: 0
    limits:
      msgs: 50000
      msg_bytes: 65536
      # 64kb * 50000 ~ 3Gb
      bytes: 3276800000
      # 60*60*24*3 = 3d
      age: 259200

database:
  uri: postgresql://postgres:changemenow@postgres/postgres?connect_timeout=30&application_name=kanthor.database

cache:
  uri: redis://redis:6379/1
  time_to_live: 300000

datastore:
  uri: postgresql://postgres:postgres@postgres/postgres?connect_timeout=30&application_name=kanthor.datastore

# services
migration:
  source: file://./migration/scripts/sql

dataplane:
  grpc:
    addr: ":8081"
  metrics:
    enable: true
    exporter:
      addr: ":9091"

scheduler:
  subscriber:
    topic: schedule
    group: default
    filter_subject: kanthor.default.msg.>
    temporary: true
    max_deliver: 1
  metrics:
    enable: true
    exporter:
      addr: ":9092"

dispatcher:
  subscriber:
    topic: dispatch
    group: default
    filter_subject: kanthor.default.req.>
    temporary: true
    max_deliver: 1
  sender:
    timeout: 3000
    retry:
      count: 1
      wait_time: 500
      wait_time_max: 3000
  circuit_breaker:
    timeout: 6000
    sleep_window: 300000
    error_percent_threshold: 25
  metrics:
    enable: true
    exporter:
      addr: ":9093"