#!/usr/bin/env bash
set -e

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
MAKEFILE="$SCRIPT_DIR/../../Makefile"

make -f "$MAKEFILE" wire

make -f "$MAKEFILE" docs