#!/usr/bin/env bash
set -e

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

sh "$SCRIPT_DIR/../ci_vet.sh"
sh "$SCRIPT_DIR/../gen_docs.sh"
sh "$SCRIPT_DIR/../gen_ioc.sh"
ls "$SCRIPT_DIR/../../**/checksum" | xargs git add