// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/scrapnode/kanthor/infrastructure/config"
	"github.com/scrapnode/kanthor/infrastructure/database"
	"github.com/scrapnode/kanthor/infrastructure/logging"
	"github.com/scrapnode/kanthor/infrastructure/msgbroker"
)

// Injectors from wire.go:

func InitializeLogger(conf config.Provider) (logging.Logger, error) {
	logger, err := logging.New(conf)
	if err != nil {
		return nil, err
	}
	return logger, nil
}

func InitializeMsgBroker(conf config.Provider) (msgbroker.MsgBroker, error) {
	logger, err := InitializeLogger(conf)
	if err != nil {
		return nil, err
	}
	msgBroker, err := msgbroker.New(conf, logger)
	if err != nil {
		return nil, err
	}
	return msgBroker, nil
}

func InitializeDatabase(conf config.Provider) (database.Database, error) {
	logger, err := InitializeLogger(conf)
	if err != nil {
		return nil, err
	}
	databaseDatabase, err := database.New(conf, logger)
	if err != nil {
		return nil, err
	}
	return databaseDatabase, nil
}
