global:
  scrape_interval: 30s
  scrape_timeout: 3s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'dataplane:8080'
          - 'scheduler:8080'
          - 'dispatcher:8080'