setup:
  dashboards:
    enabled: false
  kibana:
    host: '${KIBANA_HOST:kibana:5601}'

metricbeat.modules:
  - module: prometheus
    enabled: true
    period: 10s
    metricsets: ["collector"]
    hosts: ["dataplane:9190", "scheduler:9290", "dispatcher:9390"]
    metrics_path: /metrics

processors:
  - add_fields:
      target: fields
      fields:
        name: environment
        id: 'localhost'

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  ssl.certificate_authorities: '${METRICBEAT_CA}'
  ssl.certificate: '${METRICBEAT_CERT}'
  ssl.key: '${METRICBEAT_KEY}'