setup:
  dashboards:
    enabled: true
  kibana:
    host: '${KIBANA_HOST:kibana:5601}'

metricbeat.modules:
  - module: prometheus
    enabled: true
    period: 10s
    metricsets: ["collector"]
    hosts: ["dataplane:9190", "scheduler:9290", "dispatcher:9390"]
    metrics_path: /metrics

  - module: nats
    period: 10s
    enabled: true
    metricsets:
      - "connections"
      - "routes"
      - "stats"
      - "subscriptions"
    hosts: ["streaming:8222"]

  - module: redis
    enabled: true
    period: 10s
    metricsets: ["info", "key", "keyspace"]
    hosts: ["redis:6379"]
    key.patterns:
      - pattern: '*'
        limit: 20

processors:
  - add_fields:
      target: fields
      fields:
        name: environment
        id: 'localhost'

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  ssl.certificate_authorities: '${METRICBEAT_CA}'
  ssl.certificate: '${METRICBEAT_CERT}'
  ssl.key: '${METRICBEAT_KEY}'